### ISSUE TITLE
Unhandled rejection Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by blackWhaleDev** [lando/php#29]
after I did lando --clear
in every command im facing with
Unhandled rejection Error: Cannot find module 'semver'
Require stack:
- /home/blackwhaledev/.lando/plugins/@lando/php/services/php/builder.js
- /snapshot/cli/lib/lando.js
- /snapshot/cli/bin/lando.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/blackwhaledev/.lando/plugins/@lando/php/services/php/builder.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (pkg/prelude/bootstrap.js:1715:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /snapshot/cli/lib/lando.js
    at arrayMap (/snapshot/cli/node_modules/lodash/lodash.js:653:23)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at interceptor (/snapshot/cli/node_modules/lodash/lodash.js:17094:35)
    at thru (/snapshot/cli/node_modules/lodash/lodash.js:8859:14)
    at /snapshot/cli/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/snapshot/cli/node_modules/lodash/lodash.js:697:21)
From previous event:
    at /snapshot/cli/lib/lando.js
From previous event:
    at Lando.bootstrap (/snapshot/cli/lib/lando.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47

**Comment by reynoldsalec** [comment]
@blackWhaleDev looks like you were running the Lando PHP service from source in your `~/.lando/plugins` directory; this error may have occurred if you hadn't installed the PHP service's NPM dependencies (`yarn install`).

Going to close this out since it's fairly stale, but definitely re-open the issue if you had more problems/questions around this or DM me on the [Lando Slack](https://launchpass.com/devwithlando).
